### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [Kecoey/week11#1]
Looks mostly good, though I do see some hard-tabs in this project. The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have *every* file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by chrisvfritz** [comment]
Any progress here?

**Comment by Kecoey** [comment]
Oh this is week11, that makes sense now. I had this confused with my_web_app. It should be good now.

**Comment by chrisvfritz** [comment]
:+1:
